name = "daisupop"
main = "src/worker.js"
compatibility_date = "2026-07-01"
workers_dev = true

routes = [
  { pattern = "dp.f-keys.com/*", zone_name = "f-keys.com" }
]

[assets]
directory = "./dist"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "ROOM"
class_name = "DaisuPopRoom"

[[migrations]]
tag = "v0-0-1"
new_sqlite_classes = ["DaisuPopRoom"]
