#!/usr/bin/env python3
"""
============================================================
fonts - the typefaces, served from this domain
F-Keys | www.f-keys.com
------------------------------------------------------------
WHY THIS EXISTS
Sixty-one pages loaded their typefaces from fonts.googleapis
.com. A font request looks like the most harmless thing on a
page and is not: it reports the reader's IP address to Google
on every view, from every page, and it does it before any of
the page's own content renders.

Every face in use is under the SIL Open Font License, which
permits hosting. So they are hosted. This downloads them,
writes one stylesheet, and rewrites every page that pointed
at Google to point at that stylesheet instead.

The unicode-range and font-display:swap declarations are kept
exactly as Google served them, so a browser still downloads
only the subsets a page actually needs.

WORKFLOW STACK
  1. FAMILIES   - every family any page asks for
  2. download() - the woff2 files and their unicode ranges
  3. stylesheet()- one assets/fonts.css for all of them
  4. rewrite()  - repoint every <link> at the local file
  5. --verify   - no page reaches Google, no face is missing

Run:  python tools/fonts.py            (download + rewrite)
      python tools/fonts.py --verify   (CI)
============================================================
"""

import io
import os
import re
import sys
import urllib.request

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except (AttributeError, ValueError):
    pass

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, "assets", "fonts")
SHEET = os.path.join(ROOT, "assets", "fonts.css")

SKIP_DIRS = {".git", ".github", "node_modules", "dist", "build",
             "__pycache__", ".private-snapshot", ".agents", ".claude"}

# Exactly the queries the pages made, so the faces served are the faces
# that were being used - including the italics and the two weights.
FAMILIES = [
    "VT323",
    "Share+Tech+Mono",
    "Bebas+Neue",
    "Press+Start+2P",
    "Space+Mono:ital,wght@0,400;0,700;1,400",
    "Playfair+Display:ital@1",
]

# The Latin subsets. The pages are in English; pulling Cyrillic and Greek
# would be bytes nobody downloads.
KEEP = ("latin", "latin-ext")

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

LINK = '<link href="/assets/fonts.css" rel="stylesheet">'


def get(url):
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA})).read()


def faces():
    """Ask Google once per family and keep the parts we are allowed to."""
    out = []
    for family in FAMILIES:
        url = ("https://fonts.googleapis.com/css2?family=" + family +
               "&display=swap")
        css = get(url).decode("utf-8")
        for subset, body in re.findall(
                r"/\* (\S+) \*/\s*@font-face \{(.*?)\}", css, flags=re.S):
            if subset not in KEEP:
                continue
            name = re.search(r"font-family: '([^']+)'", body).group(1)
            style = re.search(r"font-style: (\w+)", body).group(1)
            weight = re.search(r"font-weight: (\d+)", body).group(1)
            src = re.search(r"url\((https://[^)]+)\)", body).group(1)
            rng = re.search(r"unicode-range: ([^;]+);", body).group(1)
            out.append({
                "family": name, "style": style, "weight": weight,
                "src": src, "range": rng, "subset": subset,
            })
    return out


def filename(face):
    return "{}-{}-{}-{}.woff2".format(
        face["family"].lower().replace(" ", "-"),
        face["weight"], face["style"], face["subset"])


def download(all_faces):
    os.makedirs(FONT_DIR, exist_ok=True)
    total = 0
    for face in all_faces:
        path = os.path.join(FONT_DIR, filename(face))
        data = get(face["src"])
        io.open(path, "wb").write(data)
        total += len(data)
        print("  {:<44} {:>7,} bytes".format(filename(face), len(data)))
    return total


def stylesheet(all_faces):
    header = """/* ============================================================
   fonts.css - every typeface this site uses, from this domain
   F-Keys | www.f-keys.com
   ------------------------------------------------------------
   Generated by tools/fonts.py. Do not edit by hand.

   These were served from fonts.googleapis.com, which reported
   the IP address of every reader to Google on every page view.
   All of these faces are SIL Open Font License 1.1, which
   permits hosting them, so nothing about reading this site is
   reported to anyone.

   unicode-range and font-display are kept as Google served
   them, so a browser still fetches only what a page needs.
   ============================================================ */
"""
    rules = []
    for face in all_faces:
        rules.append(
            "@font-face{{font-family:'{}';font-style:{};font-weight:{};"
            "font-display:swap;src:url(/assets/fonts/{}) format('woff2');"
            "unicode-range:{}}}".format(
                face["family"], face["style"], face["weight"],
                filename(face), face["range"]))
    io.open(SHEET, "w", encoding="utf-8", newline="\n").write(
        header + "\n".join(rules) + "\n")


def html_files():
    out = []
    for base, dirs, names in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
        for n in names:
            if n.endswith(".html"):
                out.append(os.path.join(base, n))
    return sorted(out)


# A preconnect to a host we no longer use, and the stylesheet link
# itself. Both go; several pages carry two or three of these in a row.
PATTERNS = [
    r'\s*<link[^>]*rel="preconnect"[^>]*fonts\.(googleapis|gstatic)\.com[^>]*>',
    r'\s*<link[^>]*fonts\.(googleapis|gstatic)\.com[^>]*rel="preconnect"[^>]*>',
    r'\s*<link[^>]*href="https://fonts\.googleapis\.com/css2\?[^"]*"[^>]*>',
]

# Pixel Staff asked for its faces from inside a <style> block instead of a
# <link>, which is the same request wearing different clothes. Rewritten
# in place, because a bare @import removal would take the faces with it.
IMPORT = (r"""@import\s+url\((['"]?)https://fonts\.googleapis\.com/css2\?"""
          r"""[^)]*\1\)\s*;""")


# Key-J's desktop build loads its renderer with Electron's loadFile, so
# the page is a file:// URL and a root-absolute href resolves to the root
# of the drive. app.html and desktop/src/index.html must also stay byte
# identical, which rules out giving each a path of its own depth. One
# relative path satisfies both - /keyj/../assets on the web, and
# desktop/src/../assets in the app - once the faces are mirrored there.
ELECTRON_PAIR = (os.path.join("keyj", "app.html"),
                 os.path.join("keyj", "desktop", "src", "index.html"))
ELECTRON_MIRROR = os.path.join(ROOT, "keyj", "desktop", "assets")


def href_for(path):
    return ("../assets/fonts.css"
            if os.path.relpath(path, ROOT) in ELECTRON_PAIR
            else "/assets/fonts.css")


def rewrite():
    changed = []
    for path in html_files():
        s = io.open(path, encoding="utf-8").read()
        original = s
        href = href_for(path)
        link = '<link href="{}" rel="stylesheet">'.format(href)

        had_link = any(re.search(p, s, flags=re.I) for p in PATTERNS)
        for p in PATTERNS:
            s = re.sub(p, "", s, flags=re.I)
        # an @import points at the local sheet rather than being deleted,
        # so the page keeps the faces it was asking for
        s = re.sub(IMPORT, "@import url('{}');".format(href), s, flags=re.I)
        if s == original:
            continue
        # only a page that had a <link> gets one back; a page that asked
        # from inside a <style> block has already been repointed there
        if had_link and link not in s and "</head>" in s:
            s = s.replace("</head>", link + "\n</head>", 1)
        s = normalise(s, href, link)
        io.open(path, "w", encoding="utf-8", newline="\n").write(s)
        changed.append(os.path.relpath(path, ROOT).replace("\\", "/"))

    # A page already repointed by an earlier run has no Google link left
    # to match on, so the loop above skips it and never notices that its
    # href is wrong for where it sits. Running this tool twice must reach
    # the same place as running it once.
    for path in html_files():
        s = io.open(path, encoding="utf-8").read()
        if "assets/fonts.css" not in s:
            continue
        href = href_for(path)
        fixed = normalise(s, href, '<link href="{}" rel="stylesheet">'.format(href))
        if fixed != s:
            io.open(path, "w", encoding="utf-8", newline="\n").write(fixed)
            name = os.path.relpath(path, ROOT).replace("\\", "/")
            if name not in changed:
                changed.append(name)
    return changed


def normalise(s, href, link):
    """One link, with the href correct for this page's depth."""
    s = re.sub(r'(?:\.\./)*(?:/)?assets/fonts\.css', href, s)
    # a page can end up with the link twice: once where the Google link
    # was, once appended before </head>
    while s.count(link) > 1:
        s = s.replace("\n" + link, "", 1) if "\n" + link in s \
            else s.replace(link, "", 1)
    # a page that imports the sheet from inside its own <style> is already
    # asking for it, and does not need a <link> saying so again
    if re.search(r"@import\s+url\(['\"]?" + re.escape(href), s):
        s = s.replace("\n\n" + link, "").replace("\n" + link, "")
    return s


def mirror():
    """The desktop app ships only what is under desktop/, so the faces it
    asks for have to be under desktop/ as well."""
    import shutil
    target = os.path.join(ELECTRON_MIRROR, "fonts")
    os.makedirs(target, exist_ok=True)
    for name in os.listdir(FONT_DIR):
        shutil.copyfile(os.path.join(FONT_DIR, name),
                        os.path.join(target, name))
    shutil.copyfile(SHEET, os.path.join(ELECTRON_MIRROR, "fonts.css"))
    return len(os.listdir(target)) + 1


def verify():
    problems = []
    if not os.path.exists(SHEET):
        problems.append("assets/fonts.css is missing")
    else:
        sheet = io.open(SHEET, encoding="utf-8").read()
        for m in re.findall(r"url\(/assets/fonts/([^)]+)\)", sheet):
            if not os.path.exists(os.path.join(FONT_DIR, m)):
                problems.append("fonts.css points at a missing file: " + m)
        # every family a page names must actually have a face here
        for family in ("VT323", "Share Tech Mono", "Bebas Neue",
                       "Press Start 2P", "Space Mono", "Playfair Display"):
            if "font-family:'{}'".format(family) not in sheet:
                problems.append("no face for " + family)

    for path in html_files():
        s = io.open(path, encoding="utf-8").read()
        s = re.sub(r"<!--.*?-->", " ", s, flags=re.S)     # comments do not load
        if re.search(r"fonts\.(googleapis|gstatic)\.com", s):
            problems.append("still reaches Google: " +
                            os.path.relpath(path, ROOT).replace("\\", "/"))

    # the desktop app resolves ../assets against desktop/src, so the
    # mirror is load-bearing rather than a convenience copy
    for page in ELECTRON_PAIR:
        full = os.path.join(ROOT, page)
        if os.path.exists(full) and "/assets/fonts.css" in io.open(
                full, encoding="utf-8").read().replace("../assets", "REL"):
            problems.append(page.replace("\\", "/") +
                            " uses a root-absolute font path, which is "
                            "file:///assets in Electron")
    if not os.path.exists(os.path.join(ELECTRON_MIRROR, "fonts.css")):
        problems.append("keyj/desktop/assets/fonts.css is missing - the "
                        "packaged app has no faces")

    for p in problems:
        print("fonts:", p)
    print("fonts: ok" if not problems else
          "fonts: {} FAILED".format(len(problems)))
    return 1 if problems else 0


def main():
    if "--verify" in sys.argv:
        return verify()

    print("fonts: fetching")
    all_faces = faces()
    total = download(all_faces)
    stylesheet(all_faces)
    print("  {:<44} {:>7,} bytes total".format("assets/fonts.css", total))

    changed = rewrite()
    copied = mirror()
    print("fonts: {} faces, {} pages repointed, {} mirrored for the "
          "desktop app".format(len(all_faces), len(changed), copied))
    return 0


if __name__ == "__main__":
    sys.exit(main())
