/*
============================================================
build - the npm half, lifted from the same source as the rest
F-Keys | www.f-keys.com
------------------------------------------------------------
WHY THIS EXISTS
The tablature reader and the note conversions exist twice
already: in keyj/app.html, which the browser runs, and in
keyj-cli, which is published to PyPI. keyj-cli/tests/
test_parity.py diffs them on every build, because Key-J has
already shipped three defects that existed only because two
copies of one thing drifted.

Publishing to npm by hand would make a third copy and a third
chance to drift. So this does not copy anything. It lifts the
same functions the parity test lifts, out of the same file,
and writes a module. app.html stays the source; the wheel, the
browser and the package all agree because all three come from
it.

WHAT IS LIFTED
Only the pure part: reading tablature and converting notes.
No DOM, no Web Audio, no recording - those are the app, and
they are not reusable.

Run:  node keyj-js/build.js
      node keyj-js/build.js --check    (CI: is the output current?)
============================================================
*/

var fs = require("fs");
var path = require("path");

var ROOT = path.join(__dirname, "..");
var APP = path.join(ROOT, "keyj", "app.html");
var OUT = path.join(__dirname, "index.js");

/* The same list keyj-cli/tests/test_parity.py holds. If one grows a
   function the other does not, the parity test is what notices. */
var WANTED = ["midiToName", "midiToFreq", "nameToFreq",
              "looksLikeTab", "readFrets", "parseTab", "parseTyped"];

/* Brace matching rather than a regular expression, because a function
   body containing a closing brace in a string is not a parse error and
   a regex would truncate it there. */
function extract(source, name) {
  var needle = "function " + name + "(";
  var i = source.indexOf(needle);
  if (i === -1) { throw new Error("not found in app.html: " + name); }

  var depth = 0, j = source.indexOf("{", i);
  var start = j;
  while (j < source.length) {
    if (source[j] === "{") { depth += 1; }
    else if (source[j] === "}") {
      depth -= 1;
      if (depth === 0) { return source.slice(i, j + 1); }
    }
    j += 1;
  }
  throw new Error("unbalanced braces in " + name);
}

/* The constant block the conversions rely on: NOTE_NAMES through the end
   of the MAX_CHARS line, which is the span the parity test takes. */
function constants(source) {
  var i = source.indexOf("var NOTE_NAMES = ['C',");
  if (i === -1) { throw new Error("NOTE_NAMES not found in app.html"); }
  var m = source.indexOf("var MAX_CHARS", i);
  if (m === -1) { throw new Error("MAX_CHARS not found in app.html"); }
  var end = source.indexOf(String.fromCharCode(10), m);
  return source.slice(i, end);
}


function block(source, startMarker, endMarker) {
  var i = source.indexOf(startMarker);
  if (i === -1) { throw new Error("not found: " + startMarker); }
  var j = source.indexOf(endMarker, i);
  if (j === -1) { throw new Error("no end for: " + startMarker); }
  return source.slice(i, j + endMarker.length);
}

function build() {
  var src = fs.readFileSync(APP, "utf8");

  var parts = [
    "/* Generated by keyj-js/build.js from keyj/app.html.",
    "   Do not edit. The browser app is the source; this is lifted from it",
    "   so the package, the wheel and the page cannot disagree. */",
    "",
    block(src, "var TUNINGS = {", "};"),
    "",
    /* Everything from NOTE_NAMES to the end of the MAX_CHARS line: the
       same span keyj-cli/tests/test_parity.py takes. Stopping at the
       first newline drops MAX_CHARS, and parseTab references it - which
       is exactly the kind of gap the smoke test below exists to find. */
    constants(src),
    ""
  ];

  WANTED.forEach(function (name) {
    parts.push(extract(src, name));
    parts.push("");
  });

  parts.push("module.exports = {");
  parts.push("  TUNINGS: TUNINGS,");
  parts.push("  NOTE_NAMES: NOTE_NAMES,");
  WANTED.forEach(function (name) {
    parts.push("  " + name + ": " + name + ",");
  });
  parts.push("};");
  parts.push("");

  return parts.join("\n");
}

function main() {
  var generated = build();

  if (process.argv.indexOf("--check") !== -1) {
    var existing = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : null;
    if (existing !== generated) {
      console.log("keyj-js: index.js is stale - run node keyj-js/build.js");
      console.log("         (app.html changed and the package did not)");
      process.exit(1);
    }
    console.log("keyj-js: index.js matches app.html");
    return;
  }

  fs.writeFileSync(OUT, generated);
  console.log("keyj-js: wrote index.js, " + WANTED.length +
              " functions lifted from app.html");
}

main();
