/* Generated by keyj-js/build.js from keyj/app.html.
   Do not edit. The browser app is the source; this is lifted from it
   so the package, the wheel and the page cannot disagree. */

var TUNINGS = {
    'Standard (EADGBe)': [64, 59, 55, 50, 45, 40],
    'Drop D':            [64, 59, 55, 50, 45, 38],
    'Eb Standard':       [63, 58, 54, 49, 44, 39],
    'D Standard':        [62, 57, 53, 48, 43, 38],
    'DADGAD':            [62, 57, 55, 50, 45, 38],
    'Open G':            [62, 59, 55, 50, 43, 38],
    '7-string (B)':      [64, 59, 55, 50, 45, 40, 35],
    'Bass (4)':          [43, 38, 33, 28]
  };

var NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];
  var MAX_CHARS = 200000;          // a tab this long is not a tab

function midiToName(n) { return NOTE_NAMES[((n % 12) + 12) % 12] + (Math.floor(n / 12) - 1); }

function midiToFreq(n) { return 440 * Math.pow(2, (n - 69) / 12); }

function nameToFreq(name) {
    var m = /^([A-Ga-g])([#b]?)(-?\d+)$/.exec(String(name).trim());
    if (!m) return null;
    var base = { c: 0, d: 2, e: 4, f: 5, g: 7, a: 9, b: 11 }[m[1].toLowerCase()];
    if (m[2] === '#') base += 1;
    if (m[2] === 'b') base -= 1;
    return midiToFreq(base + (parseInt(m[3], 10) + 1) * 12);
  }

function looksLikeTab(line) {
    var body = line.replace(/^\s*[A-Ga-g#b]{0,2}\s*\|/, '');
    var dashes = (body.match(/-/g) || []).length;
    return dashes >= 4 && /[-|]/.test(body);
  }

function readFrets(line) {
    var body = line.replace(/^\s*[A-Ga-g#b]{0,2}\s*\|/, function (m) {
      return new Array(m.length + 1).join(' ');       // keep column alignment
    });
    var out = [], i = 0;
    while (i < body.length) {
      if (body[i] >= '0' && body[i] <= '9') {
        var start = i, digits = '';
        while (i < body.length && body[i] >= '0' && body[i] <= '9' && digits.length < 2) {
          digits += body[i]; i++;
        }
        var fret = parseInt(digits, 10);
        if (fret <= 24) out.push({ col: start, fret: fret });
      } else { i++; }
    }
    return out;
  }

function parseTab(text, tuningName, capo) {
    var report = { notes: [], strings: 0, blocks: 0, skipped: [], tuning: tuningName, capo: capo };
    if (!text || !text.trim()) { report.error = 'Nothing pasted yet.'; return report; }
    if (text.length > MAX_CHARS) { report.error = 'That is too long to be tablature.'; return report; }

    var open = TUNINGS[tuningName];
    if (!open) { report.error = 'Unknown tuning.'; return report; }

    var lines = text.replace(/\r/g, '').split('\n');
    var i = 0, events = [];
    while (i < lines.length) {
      if (!looksLikeTab(lines[i])) { i++; continue; }
      var block = [];
      while (i < lines.length && looksLikeTab(lines[i])) { block.push(lines[i]); i++; }

      // A block should be one full set of strings. Anything else is
      // reported rather than guessed at.
      if (block.length !== open.length) {
        report.skipped.push(block.length + ' line(s) — expected ' + open.length +
                            ' strings for ' + tuningName);
        continue;
      }
      report.blocks++;
      report.strings = open.length;
      var offset = report.blocks === 1 ? 0 : events.length ? 100000 * report.blocks : 0;
      block.forEach(function (line, si) {
        readFrets(line).forEach(function (f) {
          events.push({ col: f.col + offset, string: si, midi: open[si] + f.fret + capo });
        });
      });
    }

    if (!report.blocks) {
      report.error = 'No tablature found. Expect ' + open.length +
                     ' lines of dashes and fret numbers.';
      return report;
    }

    // Column order first, then low string to high so a chord rolls upward.
    events.sort(function (a, b) { return a.col - b.col || b.string - a.string; });
    report.notes = events.map(function (e) {
      return { name: midiToName(e.midi), freq: midiToFreq(e.midi) };
    });
    return report;
  }

function parseTyped(text) {
    var toks = String(text).split(/[\s,|]+/).filter(Boolean);
    var out = [], bad = [];
    toks.forEach(function (t) {
      var f = nameToFreq(t);
      if (f) out.push({ name: t.toUpperCase(), freq: f }); else bad.push(t);
    });
    return { notes: out, skipped: bad };
  }

module.exports = {
  TUNINGS: TUNINGS,
  NOTE_NAMES: NOTE_NAMES,
  midiToName: midiToName,
  midiToFreq: midiToFreq,
  nameToFreq: nameToFreq,
  looksLikeTab: looksLikeTab,
  readFrets: readFrets,
  parseTab: parseTab,
  parseTyped: parseTyped,
};
